default: &default
  host: localhost
  port: 5432
  adapter: postgresql
  user: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: homelesscop_dev

test:
  <<: *default
  database: homelesscop_test

production:
  <<: *default
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] || 5432 %>
  user: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  database: <%= ENV["PG_DATABASE"] %>
